config/routes.rb
Rails.application.routes.draw do

  root "site#index"

  resources :owners do
  	resources :pets, only: [:index, :new, :create]
  end
  resources :pets, only: :show

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/models/owner.rb
class Owner < ActiveRecord::Base
	has_many :pets

  # TODO: add association to pets

  # TODO: add association to appointments (through pets)

  # TODO: add validations
  validates :first_name, presence: true, length: { maximum: 255 }
  validates :last_name, presence: true, length: { maximum: 255 }
  validates :email, presence: true, uniqueness: true, length: { maximum: 255 }
  validates :email, format: { with: /@/, message: "must include @" }

  before_save :normalize_phone_number

  # removes leading 1 and the characters (, ), -, .
  def normalize_phone_number
    # stretch
    if phone.present?
      phone.gsub!(/^1/, "")
      phone.gsub!(/[()-.]/,"")
    end
  end

end

app/models/pet.rb
class Pet < ActiveRecord::Base
  # TODO: associate with owner

  # TODO: associate with appointments

  # TODO: validate name and breed
  validates :name, presence: true, length: { maximum: 255 }
  validates :breed, presence: true

  validate :date_of_birth_cannot_be_in_the_future

  # adds an error if birth date is in the future
  def date_of_birth_cannot_be_in_the_future
    # stretch
  end

  # calculates age of pet in years
  def age
    # stretch
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  # TODO: add new action to show new appointment form
  def new
    pet_id = params[:pet_id]
    @pet = Pet.find_by(id: pet_id)
    @appointment = Appointment.new
  end

  # TODO: add create action to store new appointment in db
  def create
    pet_id = params[:pet_id]
    pet = Pet.find_by(id: pet_id)
    new_appointment = Appointment.new(appointment_params)
    if new_appointment.save
      pet.appointments << new_appointment
      redirect_to pet_path(pet)
    else
      # TODO: handle save errors and communicate issues to user
      render :new
    end
  end

  # TODO: implement strong parameters
  private
    def appointment_params
      params.require(:appointment).permit(:veterinarian, :reason, :time)
    end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def index
    @owners = Owner.all
  end

  def new
    @owner = Owner.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      redirect_to owner_path(@owner)
    else
      redirect_to new_owner_path
      flash[:error] = "Error has occur"
    end
  end

  def show
    owner_id = params[:id]

    @owner = Owner.find_by(id: owner_id)
  end

  def edit
    # stretch
  end

  def update
    # stretch
  end

  def destroy
    # stretch
  end

  # TODO: add custom appointments action for convenience

  private
  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :phone)
  end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def index
    # TODO: set up data for index view
    @owner = Owner.find_by_id(params[:owner_id])
    @pet = Pet.all

  end

  def show
    @pet = Pet.find_by_id(params[:id])
    # TODO: set up data for show view
  end

  # TODO: set up *new* method with data for new view
  def new
    @pet = Pet.new
  end

  # TODO: set up *create* method with database interactions for create
  def create
    @owner = Owner.find_by_id(params[:owner_id])
    @pet = @owner.pets.new(pet_params)
    @pet.save

    redirect_to (pet_path(@pet))
  end
  # TODO: handle save errors and communicate issues to user

  private
  def pet_params
    params.require(:pet).permit(:name, :breed, :date_of_birth)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/pets_helper.rb
module PetsHelper
  def my_format_age_helper age_in_days
    if age_in_days.nil?
      years = '?'
    else
      years = '%.1f' % age_in_days
    end
    "#{years}"
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/appointments/_form.html.erb
<h2>appointment _form partial</h2>
<p>Find me in app/views/appointments/_form.html.erb</p>
<%= form_for [@pet, @appointment] do |f| %>
  <div class="form-group">
    <%= f.text_field :veterinarian, class: "form-control", placeholder: "Veterinarian Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :reason, class: "form-control", placeholder: "Reason for Appointment" %>
  </div>
  <div class="form-group">
    <%= f.datetime_local_field :time, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Appointment", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/appointments/new.html.erb
<h1>Appointments#new</h1>
<p>Find me in app/views/appointments/new.html.erb</p>
<hr>
<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- bootstrap css -->
  <link type="text/css" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

  <!-- application stylesheet -->
  <%= stylesheet_link_tag :application, media: :all %>

  <title>RailsValidationsErrors</title>
</head>
<body>
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <% if flash[:error] %>
          <div class="notice"><%= flash[:error] %></div>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>


  <!-- application javascript file -->
  <%= javascript_include_tag :application %>
</body>
</html>

app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>
  <div class="form-group">
    <%= f.text_field :first_name, class: "form-control", placeholder: "First Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, class: "form-control", placeholder: "Email" %>
  </div>
  <div class="form-group">
    <%= f.telephone_field :phone, class: "form-control", placeholder: "Phone Number" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Owner", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/owners/appointments.html.erb
<h1>Appointments for @owner.email</h1>
<hr>
<ul class="list-group">
  <% @owner.appointments.each do |appointment| %>
    <li class="list-group-item">
      <p><strong>Pet:</strong> <%= link_to appointment.pet.name, pet_path(appointment.pet) %> </p>
      <p><strong>Time:</strong> <%= appointment.time.localtime.to_formatted_s(:short)  %></p>
      <p><strong>Veterinarian:</strong> <%= appointment.veterinarian %></p>
      <p><strong>Reason:</strong> <%= appointment.reason %></p>
    </li>
  <% end %>
</ul>

<p>Add appointments through an individual pet page!</p>

app/views/owners/edit.html.erb
<h1>Owners#edit</h1>
<p>Find me in app/views/owners/create.html.erb</p>

app/views/owners/index.html.erb
<h1>All Owners</h1>
<hr>
<% @owners.each do |owner| %>
  <p>
    <strong><%= link_to "#{owner.first_name} #{owner.last_name}", owner_path(owner) %></strong>
  </p>
<% end %>
<hr>
<%= link_to "register new owner", new_owner_path %>

app/views/owners/new.html.erb
<h1>New Owner</h1>
<hr>
<%= render "form" %>

app/views/owners/show.html.erb
<h1>Show Owner</h1>
<hr>
<p><strong>Name:</strong> <%= @owner.first_name %> <%= @owner.last_name %></p>
<p><strong>Email:</strong> <%= @owner.email %></p>
<p><strong>Phone Number:</strong> <%= @owner.phone %></p>

<%= link_to "View this owner's pets", owner_pets_path(@owner) %>

app/views/pets/_form.html.erb
<%= form_for :pet, url:owner_pets_path do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_field :breed, class: "form-control", placeholder: "Breed" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Pet", class: "btn btn-block btn-success" %>
  </div>
<% end %>

app/views/pets/edit.html.erb
<h1>Edit Pet</h1>
<hr>

app/views/pets/index.html.erb
<h1>All Pets for <%= @owner.email %></h1>
<hr>
<ul>
<% @owner.pets.each do |pet| %>
  <li>Name: <%= link_to "#{pet.name}", pet_path(pet) %></li> 

  <li>Breed: <%= pet.breed %></li>

  <li><%= link_to "register new pet", new_owner_pet_path %></li>



<% end %>
</ul>

app/views/pets/new.html.erb
<h1>New Pet</h1>
<hr>
<%= form_for @pet do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: "form-control", placeholder: "Name", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.text_area :breed, class: "form-control", placeholder: "Breed" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save Pet", class: "btn btn-block btn-default" %>
  </div>
<% end %>

app/views/pets/show.html.erb
<h1>Show Pet</h1>
<hr>
<p><strong>Name:</strong> <%= @pet.name %></p>
<p><strong>Breed:</strong> <%= @pet.breed %></p>

app/views/site/index.html.erb
<h1>Site#index</h1>
<p>Find me in app/views/site/index.html.erb</p>
<%= link_to "see all owners", owners_path %>